import type { Metadata } from 'next';
import { Geist, Outfit, JetBrains_Mono } from 'next/font/google';
import './globals.css';

//* Used for Body Text and Paragraphs
const geistSans = Geist({
   variable: '--font-geist-sans',
   subsets: ['latin'],
});

//* Used for Headers and Titles
const outfit = Outfit({
   variable: '--font-outfit',
   subsets: ['latin'],
});

//* Used for Technical Label and Codes
const jetBrainsMono = JetBrains_Mono({
   variable: '--font-space-grotesk',
   subsets: ['latin'],
});

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body
            className={`${geistSans.variable} ${outfit.variable} ${jetBrainsMono.variable} antialiased`}
         >
            {children}
         </body>
      </html>
   );
}
